# Test your FastAPI endpoints
# https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/competencies
Accept: application/json

###

